### ISSUE TITLE
在多个协程下会报并发问题，是不是不支持并行测试？

### ISSUE THREAD

**Issue by followroger** [bytedance/mockey#53]

**Comment by Sychorius** [comment]
mock是全局生效的，一般不建议同时跑多个测试用例

**Comment by followroger** [comment]
因为是用于其它场景，需要同时跑，那会有并发问题吗？

**Comment by xhd2015** [comment]
可以尝试一下xgo，这是一个支持并发的mock框架https://github.com/xhd2015/xgo

**Comment by Sychorius** [comment]
@followroger 本身执行时不会有并发问题，但是在mock的Build和Unpatch执行中会有
一般不建议把monkey patch技术用于其他场景，因为它受内联优化、go版本等影响较大
在线上等生产场景使用monkey patch需要对其可能产生的影响有清晰的了解
