### ISSUE TITLE
support run single test case in ide

### ISSUE THREAD

**Issue by jessin20161124** [bytedance/mockey#56]
**Is your feature request related to a problem? Please describe.**

No
**Describe the solution you'd like**

使用mockey.PatchConvey，目前不支持goland单独跑，需要支持下，类似于gotest的方式

**Describe alternatives you've considered**

**Additional context**

**Comment by pWoLiAn** [comment]
![Image](https://github.com/user-attachments/assets/3263faf0-bd56-4182-a246-a6dda26786d9)

![Image](https://github.com/user-attachments/assets/e8daefd0-2fe7-493b-89b1-36c246bf1261)

gutter icons for running individual cases is missing when using mockey.PatchConvey instead of t.Run in goland

**Comment by Sychorius** [comment]
@pWoLiAn  `PatchConvey` = `convey.Convey` + `auto unpatching`
