### ISSUE TITLE
Feature request: support mocking instance method by default

### ISSUE THREAD

**Issue by peter-wangxu** [bytedance/mockey#65]
**Is your feature request related to a problem? Please describe.**
yes

when I was mocking a method of a struct instance (ex foo := new(MyFoo)) like below:

```golang

type MyFoo struct {
   Value int
}

func (f *MyFoo) MethodA() int {
   return f.Value
}

foo := new(MyFoo)
mockey.Mock(foo.MethodA).Return(123).Build()

```

mocking was not happening as expected, and even no error message or error indicates the mock is not successfully

**Describe the solution you'd like**

the mock shall happen just as mock the struct

```
mockey.Mock(MyFool.MethodA).Return(123).Build()

```
**Describe alternatives you've considered**

i found a workaround by `mockey.GetMethod`, any thought on my query?
**Additional context**

**Comment by Sychorius** [comment]
@peter-wangxu 
`GetMethod` resolve a certain public method from an instance. It's not guaranteed 100% success when trying to resolve a private method.
For usage you can refer to https://github.com/bytedance/mockey/blob/main/mock_test.go#L382 
If you want to just mocks on certain instance, you need to use it with `When` and `Origin` , see https://github.com/bytedance/mockey/blob/main/mock_test.go#L167

**Comment by peter-wangxu** [comment]
Possible to assert this unsupported case `mockey.Mock(foo.MethodA).Return(123).Build()`

or adds this as a new feature?
