### ISSUE TITLE
Address Dependency Operational Risks

### ISSUE THREAD

**Issue by Krunal-Thakkar** [bytedance/mockey#70]
Hi Team,

We've identified a few dependencies in your project that might benefit from an update:

**github.com/smartystreets/goconvey v1.6.4(High):** This version was released on August 1, 2019. Updating to a newer version could potentially address compatibility issues or security vulnerabilities with newer systems or frameworks.

**Indirect dependencies:**
```
    - gopherjs 20181205-snapshot-0766667c (High)
    - golang.org/x/arch v0.0.0-20201008161808-52c3e6f60cff (Medium)
    - github.com/smartystreets/assertions v0.0.0-20180927180507-b2de0cb4f26d (High)
```

Updating these dependencies could improve overall security and compatibility.

Would you be open to discussing potential upgrade paths for these dependencies?Please let us know if you have any questions or require further information.

Thanks

**Comment by Sychorius** [comment]
Thanks for the information, we'll update our direct dependencies in next release.
Those dependencies are not crucial, you can use `replace` in `go.mod` for now, like this:
```go
replace github.com/smartystreets/goconvey => github.com/smartystreets/goconvey v1.8.1
```

**Comment by Sychorius** [comment]
@Krunal-Thakkar 
We found the minium Go version of goconvey was set to 1.16<sup> [\[1\]](https://github.com/smartystreets/goconvey/commit/3bb3368d798abdc09a895ee58a9f7bfe0a107bee) </sup> , so we kept it to v1.6.7 now for older Go versions support(1.13+)
You can use `replace` in go.mod to force upgrade it.

**Comment by Sychorius** [comment]
@Krunal-Thakkar  
We upgraded goconvey to v1.7.2, not latest for go1.18- support (v1.7.2+ requires at least go1.18).
If you want to use higher version, you can use `replace` in `go.mod`
