### ISSUE TITLE
The result is not as expected when use method of mockBuilder.Origin

### ISSUE THREAD

**Issue by mutezebra** [bytedance/mockey#73]
**Describe the bug**

The result after using `mockBuilder.Origin` method is not quite as expected
I'm not sure if this is a real problem or if it's by design

**To Reproduce**
code:
```go
func Foo(in string) string {
	return in
}

func TestMockXXX(t *testing.T) {
	origin := Foo
	mock := func(in string) string {
		return in + "mocked"
	}

	Mock(Foo).To(mock).Origin(&origin).Build()

	t.Log(origin("foo"))
	t.Log(Foo("foo"))
}
```

**Expected behavior**
Expected is:
> foo
> foomocked

But in fact:
> foomocked
> foomocked

By the way，If we reverse the order of logs, first call `Foo` then call `origin`
```go
	t.Log(Foo("foo"))
        t.Log(origin("foo"))
```

the result will be expected
> foomocked
> foo

the other case:
```go
        t.Log(origin("foo"))
        t.Log(origin("foo"))
```
the result is:
> foomocked
> foo

**Screenshots**

![image](https://github.com/user-attachments/assets/d1b16e4c-23c5-4945-bf49-240625344177)

**Mockey version:**

latest

**Environment:**

```text
GO111MODULE=''
GOARCH='amd64'
GOBIN=''
GOCACHE='/root/.cache/go-build'
GOENV='/root/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/home/mz/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='linux'
GOPATH='/home/mz/go'
GOPRIVATE=''
GOPROXY='https://goproxy.cn,direct'
GOROOT='/usr/local/go'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/usr/local/go/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='go1.23.2'
GODEBUG=''
GOTELEMETRY='local'
GOTELEMETRYDIR='/root/.config/go/telemetry'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='1'
GOMOD='/projects/formockey/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build316019218=/tmp/go-build -gno-record-gcc-switches'
```

**Additional context**

**Comment by Sychorius** [comment]
The initial purpose of our design of "origin" is to provide an entry for mocked functions to return to the original implementation. This is also its main usage scenario. 
When mocking a member function of a class, we need to obtain the real instance of this class. Therefore, we adopt a lazy loading way, an example is like below:
```go

type MyStruct struct {
	Name string
}

func (m *MyStruct) GetName() string {
	return m.Name
}
func TestMockXXX(t *testing.T) {
	mockey.PatchConvey("use origin as foo", t, func() {
		var origin = func() string { panic("not implemented") }
		mockey.Mock((*MyStruct).GetName).Return("anonymous").Origin(&origin).Build()

		// Note that MyStruct has not been instantiated when we mock, so we cannot get m.Name
		// So we must bind a real instance of MyStruct to origin at runtime

		// We cannot tell which instance to use before we actually call m.GetName
		// so currently we choose to not change origin's behaviour
		// origin() // panic: not implemented

		m := &MyStruct{Name: "alice"}
		t.Log(m.GetName()) // here instance 'm' is bind to 'origin'
		t.Log(origin())
	})
}
```
This may be counterintuitive in some cases (such as the one you provided). 
We may find a better way to solve it in future

**Comment by mutezebra** [comment]
I see what you mean. Thank you

**Comment by mutezebra** [comment]
> The initial purpose of our design of "origin" is to provide an entry for mocked functions to return to the original implementation. This is also its main usage scenario. When mocking a member function of a class, we need to obtain the real instance of this class. Therefore, we adopt a lazy loading way, an example is like below:
> 
> ```go
> type MyStruct struct {
> 	Name string
> }
> 
> func (m *MyStruct) GetName() string {
> 	return m.Name
> }
> func TestMockXXX(t *testing.T) {
> 	mockey.PatchConvey("use origin as foo", t, func() {
> 		var origin = func() string { panic("not implemented") }
> 		mockey.Mock((*MyStruct).GetName).Return("anonymous").Origin(&origin).Build()
> 
> 		// Note that MyStruct has not been instantiated when we mock, so we cannot get m.Name
> 		// So we must bind a real instance of MyStruct to origin at runtime
> 
> 		// We cannot tell which instance to use before we actually call m.GetName
> 		// so currently we choose to not change origin's behaviour
> 		// origin() // panic: not implemented
> 
> 		m := &MyStruct{Name: "alice"}
> 		t.Log(m.GetName()) // here instance 'm' is bind to 'origin'
> 		t.Log(origin())
> 	})
> }
> ```
> 
> This may be counterintuitive in some cases (such as the one you provided). We may find a better way to solve it in future, but now it doesn't seem so urgent.

I see what you mean. Thank you
